# Dataset and general parameters
device: "cpu"
dataset: "faces"
batch_size: 16
debug: False
dryrun: False

# Noise Scheduler parameters
schedule: "linear" 
timesteps: 300
start: 0.0001
end: 0.020

# Model shape
shape:
  # Downsampling
  - [64, 128, 256, 512, 1024]
  # Upsampling
  - [1024, 512, 256, 128, 64]

# Training parameterss
lr: 0.001
epochs: 50